services:
  minecraft:
    image: elsasssquirrel/mcserver:1.0.0-14
    container_name: minecraft_server
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - esus
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "8123:8123/tcp"
      - "19132:19132/tcp"
      - "19132:19132/udp" 
    volumes:
      # Données persistantes : world, config, plugins
      - /volume1/Docker/MCServer:/data
      # rcon-cli et entrypoint (optionnel si tu veux les surcharger)
      #- ./rcon-cli:/data/rcon-cli      
    environment:
      XMS: 512M
      MEMORY: 2048M
      # Locale (modifiable)
      LANG: fr_FR.UTF-8
      LANGUAGE: fr_FR:fr
      LC_ALL: fr_FR.UTF-8
      # Ports configurables
      MINECRAFT_PORT: 25565
      DYNMAP_PORT: 8123
      GEYSER_PORT: 19132
      # Java et PaperMC options
      JAVAFLAGS: "-Dlog4j2.formatMsgNoLookups=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200"
      PAPERMC_FLAGS: "--nojline"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.minecraft-secure.entrypoints=websecure"
      - "traefik.http.routers.minecraft-secure.rule=Host(`mcs.fbertrand.fr`)"
      - "traefik.http.routers.minecraft-secure.service=minecraft"
      - "traefik.http.services.minecraft.loadbalancer.server.port=25565"
      
networks:
  esus:
    external: true