services:
  minecraft:
    build: .
    container_name: minecraft_server
    restart: unless-stopped
    environment:
      # Locale
      LANG: fr_FR.UTF-8
      LANGUAGE: fr_FR:fr
      LC_ALL: fr_FR.UTF-8

      # Ports configurables
      MINECRAFT_PORT: 25565
      DYNMAP_PORT: 8123
      GEYSER_PORT: 19132

      # Java et PaperMC options
      JAVAFLAGS: "-Dlog4j2.formatMsgNoLookups=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200"
      PAPERMC_FLAGS: "--nojline"

    ports:
      - "${MINECRAFT_PORT}:${MINECRAFT_PORT}/tcp"
      - "${MINECRAFT_PORT}:${MINECRAFT_PORT}/udp"
      - "${DYNMAP_PORT}:${DYNMAP_PORT}/tcp"
      - "${GEYSER_PORT}:${GEYSER_PORT}/tcp"
      - "${GEYSER_PORT}:${GEYSER_PORT}/udp"

    volumes:
      - ./data:/data
      - ./rcon-cli:/data/rcon-cli
      - ./docker-entrypoint.sh:/data/docker-entrypoint.sh

    stdin_open: true
    tty: true
